### ISSUE TITLE
Provide alternative styles

### ISSUE THREAD

**Issue by brunob** [goblindegook/littlefoot#16]
The script could provide alternatives css like bigfoot especially the "number style" https://github.com/lemonmade/bigfoot/blob/master/dist/bigfoot-number.css, i managed to reproduce it with quickly with something like that :

```css
.littlefoot-footnote__button {
  position: relative;
  height: 0.95em;
  width: 1.5em;
  border-radius: 0.475em;
}

.littlefoot-footnote__button:after {
  content: attr(data-footnote-number);
  position: absolute;
  top: 50%;
  left: 50%;
  -webkit-transform: translate(-50%, -50%);
  -ms-transform: translate(-50%, -50%);
  transform: translate(-50%, -50%);
  display: block;
  font-size: 0.57em;
  font-weight: bold;
  color: rgba(110, 110, 110, 0.5);
  -webkit-transition: color 0.25s ease;
  transition: color 0.25s ease;
}

.littlefoot-footnote__button circle {
  display: none;
}
``` 

Any thoughts about this ?

PS : the readme is actually mentioning this style `For example, you may be using the numbered style of footnote`.
