### ISSUE TITLE
Enable/Disable the "Print Only" for the end of post Footnote list

### ISSUE THREAD

**Issue by chrisspiegl** [goblindegook/littlefoot#380]
I would like to see an additional option in the setup config to not hide the footnote list at the end of the post. The idea is, if someone wants to read all the footnotes at the end, they can.

I have in the meantime found a workaround to force things visible again — which isn't all that easy since they are forced invisible by the `display: none !important`.

My workaround for people that are curious, it keeps the numbers in the text invisible, but adds the list of footnotes including their index back in at the bottom:

```css
.footnotes.footnote-print-only,
.footnotes-list.footnote-print-only {
  display: block !important;
}
.footnote-item.footnote-print-only {
  display: list-item !important;
}
```
